# This playbook leaves active directory if joined
---
- hosts: localhost
  gather_facts: False
  vars_files:
  - Configs/anvil.yml
  vars:
    params:
      domain: "{{ <ENTER YOUR DOMAIN HERE> }}"
      username: "{{ <DOMAIN USER> }}"
      password: "{{ <DOMAIN USER PASSWORD> }}"
      joined: false

  tasks:
  - name: Get Active Directory configuration
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/ad"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: GET
      body: '{}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: __results
  - name: Leave Active Directory
    when: __results.json[0].joined == true
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/ad/{{ __results.json[0].uoid.uuid }}"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: PUT
      body: "{{ __results.json[0] | combine(params) }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
      timeout: 500
