---
- hosts: localhost
  gather_facts: False
  vars_files:
  - ./anvil.yml
  vars:
    av_servers: '[
      { "name": "av1","details":["icap://<IP>:1344","MCAFEE_AV"]}
    ]'
  tasks:
  - name: Remove Antivirus (ICAP) servers
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/antivirus/{{ item.name|urlencode }}"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: DELETE
      body: '{}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    with_items:
      - "{{ av_servers }}"
