# This playbook adds and activates a node-based license
---
- hosts: localhost
  gather_facts: False
  vars_files:
  - Configs/anvil.yml
  vars:
    license:
      activationId: "<INSERT ACTIVATION ID>"
      licenseType: "NODE"

  tasks:
  - name: Add and activate a license
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/licenses"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: POST
      body: '{{ license }}'
      force_basic_auth: yes
      status_code: 202
      body_format: json
      validate_certs: no
    failed_when:
      - __results.status == 500
  - name: Check if license is installed
    when: __results.status == 400
    debug:
      msg: "License is already installed."
