# This playbook add a storage node and object storage mybucket
# cloudvendor:  AMAZON_S3 | ACTIVE_SCALE_S3 | IBM_S3 | CLOUDIAN_S3 | ECS_S3 | GENERIC_S3 | GOOGLE_S3 | SCALITY_S3 | STORAGE_GRID_S3 | AZURE | GOOGLE_CLOUD | HCP_S3 | WASABI_S3 | NETAPP_S3 | SNOWFLAKE | INTERNAL_S3
# shared_volume: Set to true if used with Global File System feature
---
- hosts: localhost
  gather_facts: False
  vars_files:
  - Configs/anvil.yml
  vars:
    cloudname: <FRIENDLY NAME FOR NODE i.e. AWS_S3
    cloudvendor: <SPECIFIC VENDOR, SEE LIST ABOVE FOR EXAMPLES>
    cloudbucket: mybucket
    cloudaccesskey: ''
    cloudsecretkey: ''
    cloudvolname: <FRIENDLY NAME FOR CLOUD VOLUME>
    shared_volume: false
  tasks:
  - name: Add an Object Storage volume
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/object-storage-volumes"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: POST
      body: '{"name":"{{ cloudvolname }}","objectStoreLogicalVolume":{"_type":"OBJECT_STORE_LOGICAL_VOLUME","name":"{{ cloudbucket }}","node":{"_type":"NODE","name":"{{ cloudname }}"}},"_type":"OBJECT_STORAGE_VOLUME","node":{"_type":"NODE","name":"{{ cloudname }}"},"shared":"{{ shared_volume }}"}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
