# This playbook adds a storage node and object storage mybucket
---
- hosts: localhost
  gather_facts: False
  vars_files:
  - Configs/anvil.yml
  vars:
    node_name: "<FRIENDLY EXISTING NODE NAME>"
    node_bucket: "<BUCKET NAME>"
    object_volume_name: "My OSV"
    object_shared: "false"   # true is required for Global File System
# Parameters below this line are optional and should only be included when changing the default
#    object_native: "false"  # turns off compression, chunking and encryption. Stores objects without chunking
#    object_compression: "NO_COMPRESSION" # turns off chunk-level compression
  tasks:
  - name: Add an Object Storage volume
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/object-storage-volumes"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: POST
      body:
        name: "{{ object_volume_name }}"
        objectStoreLogicalVolume: {"_type":"OBJECT_STORE_LOGICAL_VOLUME","name":"{{ node_bucket }}","node":{"_type":"NODE","name":"{{ node_name }}"}}
        _type: "OBJECT_STORAGE_VOLUME"
        node: {"_type":"NODE","name":"{{ node_name }}"}
        shared: "{{ object_shared }}"
        compressionType: "{{ object_compression | default(omit) }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
