# This playbook adds one or more shares
# Examples
# Create a share with no export restrictions and no max share size
# {"name":"Data","path":"/data","exportOptions":[{"subnet":"*","accessPermissions":"RW","rootSquash":false}],"sizelimit":"0","size_warning_threshold":"90"}-
# Create a share limited to 10 TB in share size and exported to two different subnets
# {"name":"Data","path":"/data","exportOptions":[{"subnet":"20.20.20.0/16","accessPermissions":"RW","rootSquash":false},{"subnet":"10.10.10.0/28","accessPermissions":"RW","rootSquash":false}],"sizelimit":"10000000000000","size_warning_threshold":"90"}-
---
- hosts: localhost
  gather_facts: False
  vars_files:
  - Configs/anvil.yml
  vars:
    shares:
      name: "<SMB SHARE NAME>"
      path: "</ENTER PATH>"
      exportOptions:
      - subnet: "*"
        accessPermissions: "RW"
        rootSquash: false
      sizelimit: '0'   # Dynamic size limit based on available capacity
      size_warning_threshold: '90'
  tasks:
  - name: Create a share
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/shares"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: POST
      body:
        name: "{{ shares.name }}"
        path: "{{ shares.path }}"
        exportOptions: "{{ shares.exportOptions }}"
        shareSizeLimit: "{{ shares.sizelimit }}"
        warnUtilizationPercentThreshold: "{{ shares.size_warning_threshold }}"
      force_basic_auth: yes
      status_code: 202
      body_format: json
      validate_certs: no
    register: share_create
  - name: Check status of share create
    uri:
      url: "{{ share_create.location }}"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: GET
      body: '{}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: _result
    until: _result.json.status == "COMPLETED"
    retries: 30
    delay: 2
