# This playbook removes snapshot schedules.
# Note that snapshot schedules can only be removed if they are not in use
---
- hosts: localhost
  gather_facts: False
  vars_files:
  - ./anvil.yml
  vars:
    share_snapshots: '[
      {"name":"Data","details":["hourly","1_week"]},
      {"name":"Data","details":["daily","1_month"]},
      {"name":"Data","details":["monthly","7_years"]}
    ]'
  tasks:
  - name: Delete snapshot schedule associated with a share
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/share-snapshots/{{ item.details.0|urlencode }}"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: DELETE
      body: '{"schedule":{"name":"{{ item.details.0 }}"},"retention":{"name":"{{ item.details.1 }}"},"share":{"name":"{{ item.name }}"}}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    with_items:
      - "{{ share_snapshots }}"
