# This playbook disables and clears the syslog configuration
---
- hosts: localhost
  gather_facts: False
  vars_files:
  - Configs/anvil.yml
  vars:
    syslog:
      enabled: false
      syslogServers: null

  tasks:
  - name: Get syslog configuration
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/syslog"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: GET
      body: '{}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: __results
  - name: Disable and clear syslog configuration
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/syslog/{{ __results.json[0].uoid.uuid }}"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: PUT
      body: "{{ __results.json[0] | combine(syslog) }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
      timeout: 60
