# This playbook removes system and metadata backup job
---
- hosts: localhost
  gather_facts: False
  vars_files:
  - Configs/anvil.yml
  vars:
    backup:
      backup_path: "<EXPORT PATH>"
      backup_ip: "<NFS SERVER IP>"
      backup_schedule: "<SCHEDULE>"

  tasks:
  - name: Get System Backup configuration
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/backup"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: GET
      body: '{}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: __results
  - name: Remove System Backup configuration
# Fail when there is no system backup configured
  - fail: msg="No existing backup configured"
    when: __results.json[0] is not defined
  - name: Remove System Backup
    uri:
      url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/backup/{{ __results.json[0].uoid.uuid }}"
      user: "{{ hsuser }}"
      password: "{{ password }}"
      method: DELETE
      body: "{{ __results.json[0] | combine(backup) }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
      timeout: 60
