# This playbook configures system and metadata backup job. Note that this does not backup user data
---
- hosts: localhost
  gather_facts: False
  vars_files:
  - Configs/anvil.yml
  vars:
    backup_path: "<DESTINATION BACKUP DIRECTORY>"
    backup_ip: "<OTHER NFS SERVER IP>"
    backup_schedule: "daily"  # Daily is recommended however any schedule can be used

  tasks:
  - name: Configure System Backup
    block:
      - name: Configure System Backup
        uri:
          url: "https://{{ data_cluster_mgmt_ip }}:8443/mgmt/v1.2/rest/backup"
          user: "{{ hsuser }}"
          password: "{{ password }}"
          method: POST
          body:
            _type: "BACKUP"
            backupStorageVolume: {"ipAddress":{"address":"{{ backup_ip }}","prefixLength":32},"exportPath":"{{ backup_path }}"}
            schedule: {"name":"{{ backup_schedule }}"}
          force_basic_auth: yes
          status_code: 200
          body_format: json
          validate_certs: no
          timeout: 60
