storage:
  name: "My Isilon" # User-friendly name
  mgmtIpAddress:
    address: "<MANAGEMENT IP>"
  mgmtNodeCredentials:
    username: "<USERNAME>"
    password: "<PASSWORD>"
    cert: ""
  extendedInfo:
    snmp_community: "<SNMP STRING>" # Used for API access
  nodeType: "EMC_ISILON"
  _type: "NODE"
