storage:
  name: "My Netapp" # User-friendly name
  mgmtIpAddress:
    address: "<MANAGEMENT IP>"
  mgmtNodeCredentials:
    username: "<USERNAME>"
    password: "<PASSWORD>"
    cert: ""
  nodeType: "NETAPP_CMODE"
  _type: "NODE"
