node_name: "My Isilon"  # User-friendly name
node_ip: "<MANAGEMENT IP>"
node_type: "EMC_ISILON"
node_username: "<USERNAME>"
node_password: "<PASSWORD>"
node_extendedinfo: '{"snmp_community":"<SNMP STRING>"}'  # Used for API access
